openapi: 3.0.3
info:
  title: REST API for Hikes website
  description: Our API that...[]
  version: 0.1.9

servers:
  - url: http://api.example.com/v1
    description: Optional server description, e.g. Main (production) server
  - url: http://staging-api.example.com
    description: Optional server description, e.g. Internal staging server for testing

paths:
  /hike:
    get:
      summary: Returns a list of users.
      description: Does an SQL search for the hike database
      responses:
        "200": # status code
          description: A JSON array of hikes
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
    post:
      summary: Add a new hike.
      description: 
      responses:
        "201": # status code
          description: A JSON object 
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string