openapi: 3.0.3
info:
  title: "Hikes API"
  version: "1.0.0"

servers:
  - url: http://api.example.com/v1
    description: Optional server description, e.g. Main (production) server
  - url: http://staging-api.example.com
    description: Optional server description, e.g. Internal staging server for testing

paths:
  /:
    get:
      summary: Return a test message
      description: Simple test return to see if a connection was made.
      responses:
        "200": # status code
          description: Succesful connection
          content:
            application/json:
              schema:
                type: string
                example: Hello, World
  /hike:
    get:
      summary: Returns a list of users.
      description: Does an SQL search for the hike database
      responses:
        "200": # status code
          description: Succesful return
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    description:
                      type: string
                    location: 
                      type: string
                    createdAt:
                      type: date
                    updatedAt:
                      type: date
                    authorId:
                      type: string
  /hike/:id:
    get:
      summary: Returns the specified hike.
      description: Does an SQL search for the hike database
      parameters:
        id:
          type: integer
      responses:
        "200": # status code
          description: Returned the specified hike
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        "404": # status code
          description: Hike not found
          content:
            application/json:
              error:
                type: string
                example: "Id: {} does not exist"
  /protected/hikes:
    post:
      summary: Add a new hike to the database
      description: Through an html form send the json to add to the db
      responses:
        "201": # status code
          description: A new Hike was created
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        "404":
          description: The given json failed to match
          content:
            application/json:
              schema:
                error:
                  type: string
                  example: New Hike Failed
  /protected/hikes/:id:
    delete:
      summary: Remove the specified hike
      description: Verify this is the author, then delete the hike
      parameters:
        id:
          type: integer
      responses:
        "200": # status code
          description: Hike was succefully deleted
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        "403": # status code
          description: User not authorized
          content:
            application/json:
              error:
                type: string
                example: "Unauthroized"
        "404": # status code
          description: Hike not found
          content:
            application/json:
              error:
                type: string
                example: "Hike not found"